<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Server.UI-ce865c6c-5f0f-45f1-8440-1742c741896e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.Modal" Version="7.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MediatR" Version="12.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

</Project>
